vesion: 0.1
phases:
  install:
    commands:
      -aws cloudformation package --template-file template.yaml --s3-bucket test-bucket --output-tempalte-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml      